const DATA = [
  {
    'image': './assets/images/falconsat01.png',
    'rocket': 'Starlink 2',
    'launch_date': '16-12-2014',
    'launch_site': 'CCAES SLC 40',
    'launch_status': 'Success',
    'details': 'Last launch of the original Falcon 9 v1.0 launch vehicle',
    'rocket_summary': 'Starlink 2',
    'type': 'v1.0',
    'first_stage': 'cores 4',
    'second_stage': 'payloads: 150kg',
  },
  {
    'image': './assets/images/falcon9.png',
    'rocket': 'DemoSat',
    'launch_date': '06-07-2018',
    'launch_site': 'AAAES SLC 40',
    'launch_status': 'Success',
    'details': 'Launch of the DemoSat',
    'rocket_summary': 'DemoSat 3',
    'type': 'v1.0',
    'first_stage': 'cores 4',
    'second_stage': 'payloads: 150kg',
  },
  {
    'image': './assets/images/demosat02.png',
    'rocket': 'Falcon 9 Test',
    'launch_date': '18-03-2019',
    'launch_site': 'CCAES SLC 40',
    'launch_status': 'Success',
    'details': 'Last launch of the original Falcon 9 v1.0 launch vehicle',
    'rocket_summary': 'Falcon 9 Test',
    'type': 'v1.0',
    'first_stage': 'cores 4',
    'second_stage': 'payloads: 150kg',
  },
  {
    'image': './assets/images/crs.png',
    'rocket': 'CRS - 2',
    'launch_date': '18-03-2019',
    'launch_site': 'CCAES SLC 40',
    'launch_status': 'Success',
    'details': 'Last launch of the original Falcon 9 v1.0 launch vehicle',
    'rocket_summary': 'CRS - 2',
    'type': 'v1.0',
    'first_stage': 'cores 4',
    'second_stage': 'payloads: 150kg',
  }
];
